train_file: 'data/release_train_senti.pkl'
val_file: 'data/release_val.json'
test_file: 'data/release_test.json'

image_root: 'stickerchat/npy_stickers'

image_res: 128
batch_size_train: 4
batch_size_test: 4
val_freq: 8

warm_up: True

bert_config: 'configs/config_bert.json'
cluster_num: 60
emotion_cluster: 'cluster_feats/cluster_60.npy'

temp: 0.07
embed_dim: 256
vision_width: 768

is_ssl: 1
ssl_mlp_dim: 1024
ssl_emb_dim: 256
ssl_temp: 0.1

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 5, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}